name:                prometheus-port
version:             0.1.0.0
# github:              "githubuser/prometheus-typehell"
# license:             BSD3
# author:              "Author name here"
# maintainer:          "example@example.com"
# copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/onramp/prometheus-port#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeFamilies

library:
  source-dirs:
    - src

  exposed-modules:
    - Prometheus

  dependencies:
    - base
    - async
    - bytestring
    - containers
    - data-default
    - http-types
    - protolude
    - stm
    - text
    - time
    - wai
    - warp

  ghc-options:
    - -O2
    - -Wall
    - -Werror
    - -fno-warn-partial-type-signatures
    - -fconstraint-solver-iterations=0
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wno-unused-top-binds
    - -fno-warn-deprecations # allow undefined
    - -fno-warn-orphans

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -O2
      - -Wno-unused-local-binds
      - -Wno-unused-matches
    dependencies:
      - hspec == 2.*
      - hspec-expectations
      - HUnit
      - prometheus-port
      - protolude
      - QuickCheck
