version: 2.1

jobs:
  build:
    docker:
      - image: haskell:8.10.7-slim
    steps:
      - run:
          name: Update
          command: apt-get update && apt-get install -y openssh-client git

      - checkout

      - restore_cache:
          name: Restore dependencies
          keys:
            - cache-8.10.7-{{ checksum "prometheus-port.cabal" }}

      - run:
          name: Update dependencies
          command: cabal new-update && cabal new-install --lib

      - run:
          name: Build
          command: cabal new-build --enable-tests

      - save_cache:
          name: Cache dependencies
          key: cache-8.10.7-{{ checksum "prometheus-port.cabal" }}
          paths:
            - "/root/.cabal"
            - "dist-newstyle"

      - run:
          name: Run tests
          command: cabal new-test
